# Generated by Django 4.2.7 on 2026-08-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tasklabel_task_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='labels',
        ),
        migrations.DeleteModel(
            name='TaskLabel',
        ),
    ]
